title: karabel.org
baseurl: "/"

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
#permalink: pretty
permalink: none

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-55374057-2
disqus_shortname:
